#!/bin/bash

# Git Flow Init Function
# Initializes Git Flow in a new or existing project

# Load utilities
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./utils.sh
source "$SCRIPT_DIR/utils.sh"

# Initialize git flow in current project
init_git_flow() {
    info "Initializing Git Flow in current project..."
    
    # Check if we're in a git repository
    require_git_repository
    
    # Detect production branch
    local production_branch
    production_branch=$(get_production_branch)
    
    info "Production branch detected: $production_branch"
    
    # Check if develop branch exists
    if branch_exists "$DEVELOP_BRANCH"; then
        info "Develop branch '$DEVELOP_BRANCH' already exists"
    else
        info "Creating develop branch from $production_branch..."
        
        # Switch to production branch and pull latest
        switch_to_branch "$production_branch" || return 1
        pull_branch "$production_branch" || return 1
        
        # Create develop branch from production
        create_branch "$DEVELOP_BRANCH" "$production_branch" || return 1
        
        # Push develop branch
        push_branch "$DEVELOP_BRANCH" || return 1
        
        success "Develop branch created successfully"
    fi
    
    # Create project configuration file
    create_project_config "$production_branch"
    
    success "Git Flow initialized successfully!"
    info "Production branch: $production_branch"
    info "Develop branch: $DEVELOP_BRANCH"
    info "Configuration file: .git-flow-project"
    
    return 0
}

# Create project-specific configuration file
create_project_config() {
    local production_branch="$1"
    local project_name
    project_name=$(basename "$(pwd)")
    local config_file=".git-flow-project"
    
    if [[ -f "$config_file" ]]; then
        info "Project configuration file already exists: $config_file"
        return 0
    fi
    
    cat > "$config_file" << EOF
# Git Flow Configuration for $project_name
# This file is automatically generated by git-flow init

# Production branch for this project
PRODUCTION_BRANCH="$production_branch"

# Develop branch (standard)
DEVELOP_BRANCH="develop"

# Remote
REMOTE="origin"

# Build settings (customize as needed)
RUN_BUILD=false
BUILD_COMMAND="echo 'No build configured for this project'"

# Default confirmation
DEFAULT_CONFIRM=true
EOF
    
    success "Created project configuration: $config_file"
}

# Show init help
show_init_help() {
    echo "Git Flow Init Command"
    echo
    echo "Usage:"
    echo "  git init-flow              Initialize Git Flow in current project"
    echo "  git-flow-cli.sh init       Same as above"
    echo
    echo "What it does:"
    echo "  1. Detects production branch (main or master)"
    echo "  2. Creates develop branch if it doesn't exist"
    echo "  3. Creates .git-flow-project configuration file"
    echo "  4. Pushes develop branch to remote"
    echo
    echo "Example:"
    echo "  cd /path/to/project"
    echo "  git init-flow"
}
